'use strict';
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const net = require('net');
const express = require('express');
const db = require('./db');
const datacenters = require('./datacenters');
const cloud = require('./cloud-api');
const { calculateTrafficCost, fetchServerTraffic, formatBillingAmountLabel, formatBillingCycleFa } = require('./billing-utils');

const sessions = new Map();
const loginAttempts = new Map();
const writeAttempts = new Map();
const SESSION_COOKIE = 'hamoon_admin_session';

function jsonOk(res, data) { return res.json({ ok: true, data }); }
function jsonError(res, status, error, message) { return res.status(status).json({ ok: false, error, message }); }
function adminConfigured() { return !!(process.env.ADMIN_DASHBOARD_USER && process.env.ADMIN_DASHBOARD_PASSWORD && process.env.ADMIN_DASHBOARD_SESSION_SECRET); }
function maxAgeMs() { return Number(process.env.ADMIN_DASHBOARD_SESSION_MAX_AGE_MS || 12 * 60 * 60 * 1000); }
function safeEqual(a, b) { const ab = Buffer.from(String(a || '')); const bb = Buffer.from(String(b || '')); return ab.length === bb.length && crypto.timingSafeEqual(ab, bb); }
function parseCookies(req) { return Object.fromEntries(String(req.headers.cookie || '').split(';').filter(Boolean).map(p => { const i = p.indexOf('='); return [decodeURIComponent(p.slice(0, i).trim()), decodeURIComponent(p.slice(i + 1).trim())]; })); }
function sign(id) { return crypto.createHmac('sha256', process.env.ADMIN_DASHBOARD_SESSION_SECRET || 'missing').update(id).digest('base64url'); }
function createSession(res, actor) { const id = crypto.randomBytes(32).toString('base64url'); sessions.set(id, { actor, expires: Date.now() + maxAgeMs() }); res.setHeader('Set-Cookie', `${SESSION_COOKIE}=${encodeURIComponent(id + '.' + sign(id))}; Path=/dashboard; HttpOnly; SameSite=Lax; Max-Age=${Math.floor(maxAgeMs()/1000)}${process.env.DASHBOARD_SECURE_COOKIE === 'true' ? '; Secure' : ''}`); }
function clearSession(req, res) { const c = parseCookies(req)[SESSION_COOKIE]; if (c) sessions.delete(String(c).split('.')[0]); res.setHeader('Set-Cookie', `${SESSION_COOKIE}=; Path=/dashboard; HttpOnly; SameSite=Lax; Max-Age=0`); }
function getSession(req) { const auth = String(req.headers.authorization || ''); if (process.env.ADMIN_DASHBOARD_TOKEN && auth.startsWith('Bearer ') && safeEqual(auth.slice(7), process.env.ADMIN_DASHBOARD_TOKEN)) return { actor: 'token' }; const raw = parseCookies(req)[SESSION_COOKIE]; if (!raw) return null; const [id, sig] = String(raw).split('.'); if (!id || !sig || !safeEqual(sig, sign(id))) return null; const s = sessions.get(id); if (!s || s.expires < Date.now()) { sessions.delete(id); return null; } s.expires = Date.now() + maxAgeMs(); return s; }
function requireAuth(req, res, next) { const s = getSession(req); if (!s) return jsonError(res, 401, 'AUTH_REQUIRED', 'برای دسترسی ابتدا وارد داشبورد شوید.'); req.admin = s; next(); }
function requireAdminAction(req, res, next) { if (req.method !== 'POST') return next(); if (req.path === '/login' || req.path === '/logout') return next(); const key = req.ip || 'unknown'; const now = Date.now(); const list = (writeAttempts.get(key) || []).filter(t => now - t < 60000); if (list.length > 120) return jsonError(res, 429, 'RATE_LIMITED', 'درخواست‌های مدیریتی بیش از حد مجاز است.'); list.push(now); writeAttempts.set(key, list); if (req.headers['x-admin-action'] !== 'true') return jsonError(res, 403, 'ADMIN_HEADER_REQUIRED', 'هدر امنیتی عملیات ادمین ارسال نشده است.'); next(); }
function safeDc(dc) { return { key: dc.key, name: dc.name, provider: dc.provider || dc.apiType || 'openstack', buyEnabled: dc.buyEnabled !== false, manageEnabled: dc.manageEnabled !== false, allowedCycles: dc.allowedCycles || ['hourly','daily','weekly','monthly'], capabilities: dc.capabilities || {}, priceSource: dc.priceSource || (dc.flavors ? 'static' : 'provider'), trafficSupport: !!(dc.BILL_TRAFFIC || dc.capabilities?.traffic) }; }
function csv(rows) { const arr = Array.isArray(rows) ? rows : (rows.rows || []); const cols = Array.from(arr.reduce((s,r)=>{Object.keys(r||{}).forEach(k=>s.add(k)); return s;}, new Set())); return [cols.join(','), ...arr.map(r => cols.map(c => '"' + String(r[c] ?? '').replace(/"/g,'""') + '"').join(','))].join('\n'); }
async function audit(req, action, target, metadata) { try { await db.adminAuditLog(action, req.admin?.actor, target, metadata, req.ip); } catch (e) { console.warn('[AUDIT_FAILED]', action, e.message); } }
function capsFor(detail) { const dc = datacenters[detail.purchase.datacenter] || {}; const caps = dc.capabilities || {}; return { refresh: true, suspend: !!caps.suspendServer || dc.provider !== 'hetzner', resume: !!caps.resumeServer || dc.provider !== 'hetzner', delete: !!caps.deleteServer || caps.delete !== false, checkSsh: dc.provider === 'afracloud', resetPassword: !!caps.resetPassword || !!caps.resetPasswordBySsh, setPassword: true, revealPassword: true }; }
function providerOf(detail) { return (datacenters[detail.purchase.datacenter] || {}).provider || (datacenters[detail.purchase.datacenter] || {}).apiType || 'openstack'; }
function strongPassword() { const sets = ['ABCDEFGHJKLMNPQRSTUVWXYZ','abcdefghijkmnopqrstuvwxyz','23456789','!@#$%^&*-_=+']; const all = sets.join(''); const pick = s => s[crypto.randomInt(0, s.length)]; let p = sets.map(pick).join(''); while (p.length < 22) p += pick(all); return p.split('').sort(()=>crypto.randomInt(0,3)-1).join(''); }
function tcpCheck(host, port = 22, timeout = 4500) { return new Promise(resolve => { const s = new net.Socket(); let done = false; const finish = reachable => { if (done) return; done = true; s.destroy(); resolve({ reachable, ip: host, port, checkedAt: new Date().toISOString() }); }; s.setTimeout(timeout); s.once('connect', () => finish(true)); s.once('timeout', () => finish(false)); s.once('error', () => finish(false)); s.connect(port, host); }); }
function ipFromPurchase(p) { return p.ip || p.server_ip || p.public_ip || p.ip_address || null; }
async function providerAction(req, res, action) { const serverId = req.params.serverId; const detail = await db.getAdminServerDetail(serverId); if (!detail) return jsonError(res, 404, 'SERVER_NOT_FOUND', 'سرور پیدا نشد.'); const dc = datacenters[detail.purchase.datacenter]; if (!dc) return jsonError(res, 400, 'DATACENTER_NOT_FOUND', 'دیتاسنتر تعریف نشده است.'); const caps = capsFor(detail); if (!caps[action]) return jsonError(res, 400, 'UNSUPPORTED_ACTION', 'این عملیات برای ارائه‌دهنده پشتیبانی نمی‌شود.'); try { let result = null; const tok = await cloud.getToken(dc); if (action === 'refresh') result = await cloud.getServer(dc, tok, serverId); if (action === 'suspend') { result = await cloud.suspendServer(dc, tok, serverId); await db.adminUpdatePurchaseStatus(serverId, 'suspended'); } if (action === 'resume') { result = await cloud.resumeServer(dc, tok, serverId); await db.adminUpdatePurchaseStatus(serverId, 'active'); } if (action === 'delete') { if (!req.body.confirm) return jsonError(res, 400, 'CONFIRM_REQUIRED', 'تأیید حذف الزامی است.'); result = req.body.markOnly ? { markedOnly: true } : await cloud.deleteServer(dc, tok, serverId); await db.adminUpdatePurchaseStatus(serverId, 'deleted'); } await audit(req, `server_${action}`, { type:'server', id:serverId }, { datacenter: dc.key, success:true, markOnly: !!req.body.markOnly }); return jsonOk(res, { result }); } catch (e) { await audit(req, `server_${action}_failed`, { type:'server', id:serverId }, { datacenter: dc.key, error:e.code || e.message }); return jsonError(res, 502, 'PROVIDER_ACTION_FAILED', 'عملیات روی ارائه‌دهنده ناموفق بود.'); } }

function createDashboardApiRouter() {
  if (!adminConfigured()) console.warn('[DASHBOARD_SECURITY] ADMIN_DASHBOARD_USER/PASSWORD/SESSION_SECRET must be set; dashboard login will be disabled.');
  const router = express.Router();
  router.use(express.json({ limit: '1mb' }));
  router.post('/login', (req,res) => { const key=req.ip||'unknown'; const now=Date.now(); const list=(loginAttempts.get(key)||[]).filter(t=>now-t<15*60*1000); if(list.length>=20) return jsonError(res,429,'LOGIN_RATE_LIMITED','تلاش ورود بیش از حد مجاز است.'); list.push(now); loginAttempts.set(key,list); if(!adminConfigured()) return jsonError(res,503,'ADMIN_AUTH_NOT_CONFIGURED','ورود ادمین روی سرور تنظیم نشده است.'); const {username,password}=req.body||{}; if(!safeEqual(username,process.env.ADMIN_DASHBOARD_USER)||!safeEqual(password,process.env.ADMIN_DASHBOARD_PASSWORD)) return jsonError(res,401,'INVALID_LOGIN','نام کاربری یا رمز عبور نادرست است.'); createSession(res, username); jsonOk(res,{user:username}); });
  router.post('/logout', (req,res)=>{ clearSession(req,res); jsonOk(res,{loggedOut:true}); });
  router.use(requireAuth, requireAdminAction);
  router.get('/me', (req,res)=>jsonOk(res,{user:req.admin.actor, configured:adminConfigured()}));
  router.get('/overview', async (_req,res,next)=>{ try{jsonOk(res, await db.getAdminOverviewStats());}catch(e){next(e);} });
  router.get('/metrics/:metric/details', async (req,res,next)=>{ try{const data=await db.getAdminMetricDetails(req.params.metric, req.query); data?res.json(data):jsonError(res,404,'METRIC_NOT_FOUND','شاخص پیدا نشد.');}catch(e){next(e);} });
  router.get('/metrics/:metric/export.csv', async (req,res,next)=>{ try{const data=await db.getAdminMetricDetails(req.params.metric, {...req.query,pageSize:200}); if(!data)return jsonError(res,404,'METRIC_NOT_FOUND','شاخص پیدا نشد.'); res.type('text/csv').send(csv(data.rows));}catch(e){next(e);} });
  router.get('/search', async (req,res,next)=>{ try{jsonOk(res, await db.globalAdminSearch(req.query.q, req.query.limit));}catch(e){next(e);} });
  router.get('/charts/revenue', async (req,res,next)=>{ try{jsonOk(res, await db.getAdminRevenueStats(req.query.days));}catch(e){next(e);} });
  router.get('/charts/purchases', async (req,res,next)=>{ try{jsonOk(res, await db.getAdminPurchaseStats(req.query.days));}catch(e){next(e);} });
  router.get('/charts/servers-by-datacenter', async (_req,res,next)=>{ try{jsonOk(res, await db.getAdminDatacenterStats());}catch(e){next(e);} });
  router.get('/charts/wallet-flow', async (req,res,next)=>{ try{jsonOk(res, await db.getAdminWalletFlowStats(req.query.days));}catch(e){next(e);} });
  router.get('/stats/revenue', async (req,res,next)=>{ try{jsonOk(res, await db.getAdminRevenueStats(req.query.days));}catch(e){next(e);} });
  router.get('/stats/purchases', async (req,res,next)=>{ try{jsonOk(res, await db.getAdminPurchaseStats(req.query.days));}catch(e){next(e);} });
  router.get('/stats/datacenters', async (_req,res,next)=>{ try{jsonOk(res, await db.getAdminDatacenterStats());}catch(e){next(e);} });
  router.get('/users', async (req,res,next)=>{ try{res.json(await db.listAdminUsers(req.query));}catch(e){next(e);} });
  router.get('/users/:telegramId', async (req,res,next)=>{ try{const d=await db.getAdminUserDetail(req.params.telegramId); d?jsonOk(res,d):jsonError(res,404,'USER_NOT_FOUND','کاربر پیدا نشد.');}catch(e){next(e);} });
  router.get('/users/:telegramId/wallet', async (req,res,next)=>{ try{jsonOk(res,{balance:await db.getUserWallet(req.params.telegramId)});}catch(e){next(e);} });
  router.get('/users/:telegramId/wallet-logs', async (req,res,next)=>{ try{jsonOk(res, await db.listAdminWalletLogs({...req.query,search:req.params.telegramId}));}catch(e){next(e);} });
  router.get('/users/:telegramId/purchases', async (req,res,next)=>{ try{jsonOk(res, await db.listAdminPurchases({...req.query,userId:req.params.telegramId}));}catch(e){next(e);} });
  router.get('/users/:telegramId/servers', async (req,res,next)=>{ try{jsonOk(res, await db.listAdminServers({...req.query,userId:req.params.telegramId}));}catch(e){next(e);} });
  router.post('/users/:telegramId/credit', async (req,res,next)=>{ try{const amount=Number(req.body.amount); if(!Number.isFinite(amount)||amount<=0)return jsonError(res,400,'INVALID_AMOUNT','مبلغ نامعتبر است.'); const b=await db.adminCreditUser(req.params.telegramId, amount, req.body.description); await audit(req,'credit_user',{type:'user',id:req.params.telegramId},{amount}); jsonOk(res,{balance:b});}catch(e){next(e);} });
  router.post('/users/:telegramId/debit', async (req,res,next)=>{ try{const amount=Number(req.body.amount); if(!Number.isFinite(amount)||amount<=0)return jsonError(res,400,'INVALID_AMOUNT','مبلغ نامعتبر است.'); const b=await db.adminDebitUser(req.params.telegramId, amount, req.body.description); await audit(req,'debit_user',{type:'user',id:req.params.telegramId},{amount}); jsonOk(res,{balance:b});}catch(e){next(e);} });
  router.post('/users/:telegramId/message', async (req,res)=>{ await audit(req,'send_message',{type:'user',id:req.params.telegramId},{queued:false}); jsonOk(res,{queued:false,message:'ارسال مستقیم پیام از داشبورد در این فرایند فعال نیست.'}); });
  router.post('/users/:telegramId/shahkar/verify', async (req,res,next)=>{ try{await db.updateUserShahkar(req.params.telegramId, req.body.national_code || '', {admin_override:true}); await audit(req,'shahkar_verify',{type:'user',id:req.params.telegramId},{}); jsonOk(res,{verified:true});}catch(e){next(e);} });
  router.post('/users/:telegramId/shahkar/clear', async (req,res,next)=>{ try{if(!req.body.confirm)return jsonError(res,400,'CONFIRM_REQUIRED','تأیید الزامی است.'); await db.pool.execute('UPDATE users SET shahkar_verified=0, shahkar_verified_at=NULL, shahkar_last_response=NULL WHERE telegram_id=?',[String(req.params.telegramId)]); await audit(req,'shahkar_clear',{type:'user',id:req.params.telegramId},{}); jsonOk(res,{verified:false});}catch(e){next(e);} });
  router.get('/servers', async (req,res,next)=>{ try{const data=await db.listAdminServers(req.query); data.rows.forEach(r=>{ const dc=datacenters[r.datacenter]||{}; r.provider=dc.provider||dc.apiType||'openstack'; r.datacenter_label=dc.name||r.datacenter; r.capabilities=capsFor({purchase:r}); }); jsonOk(res,data);}catch(e){next(e);} });
  router.get('/servers/:serverId', async (req,res,next)=>{ try{const d=await db.getAdminServerDetail(req.params.serverId); if(!d)return jsonError(res,404,'SERVER_NOT_FOUND','سرور پیدا نشد.'); const dc=datacenters[d.purchase.datacenter]||{}; d.provider=providerOf(d); d.datacenter_label=dc.name||d.purchase.datacenter; d.capabilities=capsFor(d); d.purchase.ip = ipFromPurchase(d.purchase); d.audit_logs = await db.listAdminAuditLogs(80).then(rows=>rows.filter(r=>String(r.target_id)===String(req.params.serverId))).catch(()=>[]); jsonOk(res,d);}catch(e){next(e);} });
  // validated endpoints: /servers/:serverId/refresh /servers/:serverId/suspend /servers/:serverId/resume /servers/:serverId/delete
  ['refresh','suspend','resume','delete'].forEach(a=>router.post(`/servers/:serverId/${a}`, (req,res)=>providerAction(req,res,a)));
  router.post('/servers/:serverId/check-ssh', async (req,res,next)=>{ try{const d=await db.getAdminServerDetail(req.params.serverId); if(!d)return jsonError(res,404,'SERVER_NOT_FOUND','سرور پیدا نشد.'); const ip=ipFromPurchase(d.purchase); if(!ip)return jsonError(res,400,'NO_SERVER_IP','IP سرور در دیتابیس موجود نیست.'); const out=await tcpCheck(ip); await audit(req,'check_ssh',{type:'server',id:req.params.serverId},{reachable:out.reachable}); jsonOk(res,out);}catch(e){next(e);} });
  router.post('/servers/:serverId/reset-password', async (req,res,next)=>{ try{if(!req.body.confirm)return jsonError(res,400,'CONFIRM_REQUIRED','تأیید الزامی است.'); const d=await db.getAdminServerDetail(req.params.serverId); if(!d)return jsonError(res,404,'SERVER_NOT_FOUND','سرور پیدا نشد.'); const dc=datacenters[d.purchase.datacenter]||{}; if(!capsFor(d).resetPassword)return jsonError(res,400,'UNSUPPORTED_ACTION','این عملیات برای ارائه‌دهنده پشتیبانی نمی‌شود.'); if(providerOf(d)==='afracloud'){ const oldPassword=await db.getServerSecret(req.params.serverId).catch(err=>{err.safeCode=err.code; throw err;}); if(!oldPassword)return jsonError(res,400,'NO_STORED_PASSWORD','رمز قبلی ذخیره نشده است.'); const ip=ipFromPurchase(d.purchase); if(!ip)return jsonError(res,400,'NO_SERVER_IP','IP سرور در دیتابیس موجود نیست.'); const reachable=await tcpCheck(ip); if(!reachable.reachable)return jsonError(res,400,'SSH_PORT_UNREACHABLE','پورت SSH در دسترس نیست.'); return jsonError(res,400,'UNSUPPORTED_ACTION','سرویس ریست SSH در این نصب به داشبورد متصل نشده است.'); }
    const tok=await cloud.getToken(dc); const result=await cloud.resetServerPassword(dc,tok,req.params.serverId); const newPassword=result?.password || result?.rootPassword || strongPassword(); if(result?.password || result?.rootPassword) await db.upsertServerSecret({telegramId:d.purchase.telegram_id,serverId:req.params.serverId,datacenter:d.purchase.datacenter,secretValue:newPassword}); await audit(req,'reset_password',{type:'server',id:req.params.serverId},{provider:providerOf(d), stored: !!(result?.password || result?.rootPassword)}); jsonOk(res,{password:newPassword, stored:!!(result?.password || result?.rootPassword)}); }catch(e){ if(e.code==='SERVER_SECRET_KEY_MISSING'||e.safeCode==='SERVER_SECRET_KEY_MISSING')return jsonError(res,500,'SERVER_SECRET_KEY_MISSING','کلید امن ذخیره رمز روی سرور تنظیم نشده است.'); next(e);} });
  router.post('/servers/:serverId/reset-password-ssh', async (req,res,next)=>{ try{ if(!req.body.confirm)return jsonError(res,400,'CONFIRM_REQUIRED','تأیید الزامی است.'); const d=await db.getAdminServerDetail(req.params.serverId); if(!d)return jsonError(res,404,'SERVER_NOT_FOUND','سرور پیدا نشد.'); if(providerOf(d)!=='afracloud')return jsonError(res,400,'UNSUPPORTED_ACTION','این عملیات برای ارائه‌دهنده پشتیبانی نمی‌شود.'); await audit(req,'reset_password_ssh_failed',{type:'server',id:req.params.serverId},{reason:'service_not_connected'}); return jsonError(res,400,'UNSUPPORTED_ACTION','سرویس ریست SSH در این نصب به داشبورد متصل نشده است.'); }catch(e){next(e);} });
  router.post('/servers/:serverId/set-password', async (req,res,next)=>{ try{if(!req.body.confirm||!req.body.password)return jsonError(res,400,'CONFIRM_REQUIRED','رمز و تأیید الزامی است.'); const d=await db.getAdminServerDetail(req.params.serverId); if(!d)return jsonError(res,404,'SERVER_NOT_FOUND','سرور پیدا نشد.'); await db.upsertServerSecret({telegramId:d.purchase.telegram_id,serverId:req.params.serverId,datacenter:d.purchase.datacenter,secretValue:req.body.password}); await audit(req,'set_password',{type:'server',id:req.params.serverId},{stored:true}); jsonOk(res,{stored:true});}catch(e){if(e.code==='SERVER_SECRET_KEY_MISSING')return jsonError(res,500,'SERVER_SECRET_KEY_MISSING','کلید امن ذخیره رمز روی سرور تنظیم نشده است.'); next(e);} });
  router.post('/servers/:serverId/reveal-password', async (req,res,next)=>{ try{if(!req.body.confirm)return jsonError(res,400,'CONFIRM_REQUIRED','تأیید الزامی است.'); const secret=await db.getServerSecret(req.params.serverId); if(!secret)return jsonError(res,404,'NO_STORED_PASSWORD','رمز ذخیره‌شده‌ای وجود ندارد.'); await audit(req,'password_revealed',{type:'server',id:req.params.serverId},{revealed:true}); jsonOk(res,{password:secret});}catch(e){if(e.code==='SERVER_SECRET_KEY_MISSING')return jsonError(res,500,'SERVER_SECRET_KEY_MISSING','کلید امن ذخیره رمز روی سرور تنظیم نشده است.'); next(e);} });
  router.post('/servers/:serverId/update-purchase-status', async (req,res,next)=>{ try{const allowed=['active','suspended','deleted','manual','stopped']; if(!allowed.includes(String(req.body.status)))return jsonError(res,400,'INVALID_STATUS','وضعیت نامعتبر است.'); const d=await db.adminUpdatePurchaseStatus(req.params.serverId, req.body.status); await audit(req,'purchase_status_update',{type:'server',id:req.params.serverId},{status:req.body.status}); jsonOk(res,d);}catch(e){next(e);} });
  router.post('/servers/:serverId/update-status', async (req,res,next)=>{ try{const d=await db.adminUpdatePurchaseStatus(req.params.serverId, req.body.status); await audit(req,'purchase_status_update',{type:'server',id:req.params.serverId},{status:req.body.status}); jsonOk(res,d);}catch(e){next(e);} });
  router.post('/servers/attach-afra', async (req,res,next)=>{ try{const user=await db.getUser(req.body.telegram_id); if(!user)return jsonError(res,404,'USER_NOT_FOUND','کاربر پیدا نشد.'); await db.pool.execute(`INSERT INTO purchases (server_id,telegram_id,datacenter,server_name,flavor_id,amount,duration,price_per_gb,download_only,boot_method,os_label,status) VALUES (?,?,?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE telegram_id=VALUES(telegram_id), server_name=VALUES(server_name), flavor_id=VALUES(flavor_id), amount=VALUES(amount), os_label=VALUES(os_label), status=VALUES(status)`, [String(req.body.server_id),String(req.body.telegram_id),'afracloud',String(req.body.server_name||req.body.server_id),String(req.body.flavor_id||req.body.flavor_label||''),Number(req.body.monthly_price)||0,'monthly',0,0,'attached',req.body.os_label||null,'active']); if(req.body.password) await db.upsertServerSecret({telegramId:req.body.telegram_id,serverId:req.body.server_id,datacenter:'afracloud',secretValue:req.body.password}); await audit(req,'attach_afra',{type:'server',id:req.body.server_id},{telegram_id:req.body.telegram_id,passwordStored:!!req.body.password}); jsonOk(res,{attached:true});}catch(e){next(e);} });
  router.get('/wallet/logs', async (req,res,next)=>{ try{jsonOk(res, await db.listAdminWalletLogs(req.query));}catch(e){next(e);} });
  router.post('/wallet/adjust', async (req,res,next)=>{ try{const amount=Number(req.body.amount); const b=amount>=0?await db.adminCreditUser(req.body.telegram_id,amount,req.body.description):await db.adminDebitUser(req.body.telegram_id,Math.abs(amount),req.body.description); await audit(req,'wallet_adjust',{type:'user',id:req.body.telegram_id},{amount}); jsonOk(res,{balance:b});}catch(e){next(e);} });
  router.get('/purchases', async (req,res,next)=>{ try{jsonOk(res, await db.listAdminPurchases(req.query));}catch(e){next(e);} });
  router.get('/purchases/:id', async (req,res,next)=>{ try{const d=await db.getAdminServerDetail(req.params.id); d?jsonOk(res,d.purchase):jsonError(res,404,'PURCHASE_NOT_FOUND','خرید پیدا نشد.');}catch(e){next(e);} });
  router.post('/purchases/:id/status', async (req,res,next)=>{ try{const d=await db.adminUpdatePurchaseStatus(req.params.id, req.body.status); await audit(req,'purchase_status_update',{type:'purchase',id:req.params.id},{status:req.body.status}); jsonOk(res,d);}catch(e){next(e);} });
  router.post('/purchases/:id/billing', async (req,res)=>{ await audit(req,'purchase_billing_update',{type:'purchase',id:req.params.id},{}); jsonOk(res,{updated:false}); });

  router.get('/providers/:dcKey/traffic-health', async (req,res)=>{ try{const dc=datacenters[req.params.dcKey]; if(!dc)return jsonError(res,404,'DATACENTER_NOT_FOUND','دیتاسنتر پیدا نشد.'); if(!dc.TRAFFIC_API_BASE_URL)return jsonError(res,400,'TRAFFIC_NOT_SUPPORTED','API ترافیک تنظیم نشده است.'); const end=Math.floor(Date.now()/1000); const data=await fetchServerTraffic(dc, req.query.serverId || 'health-check', end-60, end); jsonOk(res,{healthy:true, shape:{received_gb:typeof data.received_gb, transmitted_gb:typeof data.transmitted_gb}});}catch(e){jsonOk(res,{healthy:false,error:e.message});} });
  router.post('/servers/:serverId/billing', async (req,res,next)=>{ try{const updated=await db.adminUpdateBilling(req.params.serverId, req.body||{}); await audit(req,'set_billing',{type:'server',id:req.params.serverId},{result:'ok'}); jsonOk(res,updated);}catch(e){next(e);} });
  router.post('/users/:telegramId/billing', async (req,res,next)=>{ try{const list=await db.listAdminServers({userId:req.params.telegramId,limit:200}); const rows=req.body.include_non_active===true?list.rows:list.rows.filter(p=>!['deleted','deletion_pending'].includes(p.status)); const out=[]; for(const pch of rows) out.push(await db.adminUpdateBilling(pch.server_id, req.body||{})); await audit(req,'set_billing_user',{type:'user',id:req.params.telegramId},{count:out.length,result:'ok'}); jsonOk(res,{updated:out.length,rows:out});}catch(e){next(e);} });
  router.post('/billing/run', async (req,res)=>{ await audit(req,'run_billing',{type:'system',id:'all'},{preview:true,result:'ok'}); jsonOk(res,{queued:false,message:'اجرای مستقیم چرخه billing از داشبورد در این نصب به صورت preview ثبت شد؛ از npm/PM2 scheduler استفاده کنید.'}); });
  router.post('/billing/run-user/:telegramId', async (req,res,next)=>{ try{const summary=await billingSummary(req.params.telegramId); await audit(req,'run_billing_user',{type:'user',id:req.params.telegramId},{preview:true,result:'ok'}); jsonOk(res,{charged:false,preview:summary});}catch(e){next(e);} });
  async function serverTrafficPreview(serverId){ const d=await db.getAdminServerDetail(serverId); if(!d) throw new Error('SERVER_NOT_FOUND'); const dc=datacenters[d.purchase.datacenter]; if(!dc) throw new Error('DATACENTER_NOT_FOUND'); const calc=await calculateTrafficCost(d.purchase, d.purchase.created_at, new Date(), dc); return { purchase:d.purchase, calculation:calc, billing_label:formatBillingAmountLabel(d.purchase.amount, d.purchase.duration), billing_cycle_fa:formatBillingCycleFa(d.purchase.duration) }; }
  async function billingSummary(telegramId){ const rows=(await db.listAdminServers({userId:telegramId,limit:200})).rows; const out=[]; for(const r of rows){ try{out.push(await serverTrafficPreview(r.server_id));}catch(e){out.push({purchase:r,error:e.message});} } return out; }
  router.post('/servers/:serverId/traffic/test', async (req,res,next)=>{ try{const out=await serverTrafficPreview(req.params.serverId); await audit(req,'traffic_test',{type:'server',id:req.params.serverId},{result:'ok'}); jsonOk(res,out);}catch(e){next(e);} });
  router.get('/servers/:serverId/traffic', async (req,res,next)=>{ try{jsonOk(res, await serverTrafficPreview(req.params.serverId));}catch(e){next(e);} });
  router.post('/users/:telegramId/traffic/test', async (req,res,next)=>{ try{const out=await billingSummary(req.params.telegramId); await audit(req,'traffic_test_user',{type:'user',id:req.params.telegramId},{count:out.length,result:'ok'}); jsonOk(res,out);}catch(e){next(e);} });
  router.get('/users/:telegramId/billing-summary', async (req,res,next)=>{ try{jsonOk(res, await billingSummary(req.params.telegramId));}catch(e){next(e);} });

  router.get('/datacenters', (_req,res)=>jsonOk(res,Object.values(datacenters).filter(dc=>dc&&dc.key).map(safeDc)));
  router.get('/datacenters/:key/health', async (req,res)=>{ const dc=datacenters[req.params.key]; if(!dc)return jsonError(res,404,'DATACENTER_NOT_FOUND','دیتاسنتر پیدا نشد.'); const health={token:false,listFlavors:false,listServers:false}; try{const tok=await cloud.getToken(dc); health.token=true; try{await cloud.listFlavors(dc,tok); health.listFlavors=true;}catch{} try{await cloud.listServers(dc,tok); health.listServers=true;}catch{} jsonOk(res,health);}catch{jsonOk(res,health);} });
  router.get('/logs/server-events', (req,res)=>{ const file=path.join(__dirname,'server_events.log'); const limit=Math.min(parseInt(req.query.limit,10)||200,500); if(!fs.existsSync(file))return jsonOk(res,[]); const lines=fs.readFileSync(file,'utf8').split('\n').filter(Boolean).slice(-limit).map(l=>l.replace(/(password|token|secret)[^,}]*/ig,'$1:[redacted]')); jsonOk(res,lines); });
  router.get('/logs/app', (_req,res)=>jsonOk(res,{message:'PM2 log reading is disabled for safety; use pm2 logs on server.'}));
  router.get('/logs/audit', async (req,res,next)=>{ try{jsonOk(res, await db.listAdminAuditLogs(req.query.limit));}catch(e){next(e);} });
  router.get('/export/users.csv', async (req,res,next)=>{ try{res.type('text/csv').send(csv(await db.listAdminUsers({...req.query,limit:200})));}catch(e){next(e);} });
  router.get('/export/servers.csv', async (req,res,next)=>{ try{res.type('text/csv').send(csv(await db.listAdminServers({...req.query,limit:200})));}catch(e){next(e);} });
  router.get('/export/wallet.csv', async (req,res,next)=>{ try{res.type('text/csv').send(csv(await db.listAdminWalletLogs({...req.query,limit:200})));}catch(e){next(e);} });
  router.get('/export/purchases.csv', async (req,res,next)=>{ try{res.type('text/csv').send(csv(await db.listAdminPurchases({...req.query,limit:200})));}catch(e){next(e);} });
  router.use((err,_req,res,_next)=>{ console.error('[DASHBOARD_API_ERROR]', err.code || err.message); jsonError(res,500,'DASHBOARD_API_ERROR','خطای داخلی داشبورد رخ داد.'); });
  return router;
}
module.exports = { createDashboardApiRouter, requireAuth, getSession, adminConfigured };
